"""adding models for art and sound

Revision ID: cef31df608fc
Revises: 661e40d9c78b
Create Date: 2025-04-10 16:51:14.672514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef31df608fc'
down_revision = '661e40d9c78b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artwork_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_audio_work_artwork_id", "artwork", ["artwork_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio_work', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artwork_id')

    # ### end Alembic commands ###
